name: C/C++ CI

on:
  push:
    branches: [ feat/test-unity ]
  pull_request:
    branches: [ feat/test-unity ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ammaraskar/gcc-problem-matcher@master
    - name: Run tests
      run: sudo apt-get install libpng-dev ruby-full; cd tests; python ./main.py
